
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 07rrk
 */

public class CatatanHarianFrame extends javax.swing.JFrame {
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CatatanHarianFrame.class.getName());
    
    private final DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form CatatanHarianFrame
     */
    public CatatanHarianFrame() {
        initComponents();
        listCatatan.setModel(listModel);   
        muatDaftarCatatan();
        scrollList.setViewportView(listCatatan);
    listCatatan.addListSelectionListener(evt -> {
    if (!evt.getValueIsAdjusting()) {
        String selected = listCatatan.getSelectedValue();
        if (selected != null) {
            bukaCatatan(selected);
        }
    }
});
    File folder = new File("catatan");
if (!folder.exists()) {
    folder.mkdirs();
}

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        lblJudul = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        scrollIsi = new javax.swing.JScrollPane();
        txtIsi = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnImpor = new javax.swing.JButton();
        btnEkspor = new javax.swing.JButton();
        scrollList = new javax.swing.JScrollPane();
        listCatatan = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Catatan Harian - PBO2 UTS");

        lblcari.setText("Cari:");

        txtCari.setColumns(20);

        btnCari.setText("Cari");

        lblJudul.setText("Judul :");

        txtJudul.setColumns(30);

        txtIsi.setColumns(40);
        txtIsi.setRows(10);
        txtIsi.setWrapStyleWord(true);
        scrollIsi.setViewportView(txtIsi);

        btnTambah.setText("Tambah Baru");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan / Update");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnImpor.setText("Impor (.txt)");
        btnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImporActionPerformed(evt);
            }
        });

        btnEkspor.setText("Ekspor (.txt)");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImpor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEkspor)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJudul))
                            .addComponent(scrollIsi))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJudul)
                            .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollIsi, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnSimpan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnHapus))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnImpor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnEkspor))))
                    .addComponent(scrollList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        txtJudul.setText("");
        txtIsi.setText("");
        txtJudul.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
       String judul = txtJudul.getText().trim();
String isi = txtIsi.getText();

if (judul.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Judul tidak boleh kosong!");
    return;
}

try {
    File folder = new File("catatan");
    if (!folder.exists()) folder.mkdir();

    FileWriter writer = new FileWriter("catatan/" + judul + ".txt");
    writer.write(isi);
    writer.close();

    if (!listModel.contains(judul)) {
        listModel.addElement(judul);
    }

    JOptionPane.showMessageDialog(this, "Catatan disimpan!");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal menyimpan catatan!");
}
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        hapusCatatan();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporActionPerformed
        // TODO add your handling code here:
        eksporCatatan();
    }//GEN-LAST:event_btnEksporActionPerformed

    private void btnImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImporActionPerformed
        // TODO add your handling code here:
        imporCatatan();
    }//GEN-LAST:event_btnImporActionPerformed

private void imporCatatan() {
    try {
        // pilih file
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        BufferedReader br = new BufferedReader(new FileReader(file));

        String line;
        String currentJudul = "";
        StringBuilder isi = new StringBuilder();

        while ((line = br.readLine()) != null) {
            if (line.startsWith("== ") && line.endsWith(" ==")) {

                // simpan catatan sebelumnya
                if (!currentJudul.isEmpty()) {
                    FileWriter writer = new FileWriter("catatan/" + currentJudul + ".txt");
                    writer.write(isi.toString());
                    writer.close();

                    if (!listModel.contains(currentJudul)) {
                        listModel.addElement(currentJudul);
                    }
                }

                // reset & ambil judul baru
                currentJudul = line.substring(3, line.length() - 3).trim();
                isi = new StringBuilder();

            } else {
                isi.append(line).append("\n");
            }
        }

        // simpan catatan terakhir
        if (!currentJudul.isEmpty()) {
            FileWriter writer = new FileWriter("catatan/" + currentJudul + ".txt");
            writer.write(isi.toString());
            writer.close();

            if (!listModel.contains(currentJudul)) {
                listModel.addElement(currentJudul);
            }
        }

        br.close();
        JOptionPane.showMessageDialog(this, "Impor selesai!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengimpor catatan!");
    }
}
    
    
private void eksporCatatan() {
    try {
        File folder = new File("catatan");
        File[] files = folder.listFiles((dir, name) -> name.endsWith(".txt"));

        if (files == null || files.length == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada catatan untuk diekspor!");
            return;
        }

        FileWriter writer = new FileWriter("backup_catatan.txt");

        for (File f : files) {
            writer.write("== " + f.getName().replace(".txt", "") + " ==\n");
            BufferedReader br = new BufferedReader(new FileReader(f));
            String line;
            while ((line = br.readLine()) != null) {
                writer.write(line + "\n");
            }
            writer.write("\n\n");
            br.close();
        }

        writer.close();
        JOptionPane.showMessageDialog(this, "Export selesai! File: backup_catatan.txt");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal melakukan export!");
    }
}
    
    
private void muatDaftarCatatan() {
    File folder = new File("catatan");
    if (!folder.exists()) {
        folder.mkdir(); // buat folder jika belum ada
    }

    listModel.clear();

    File[] files = folder.listFiles((dir, name) -> name.endsWith(".txt"));
    if (files != null) {
        for (File f : files) {
            String nama = f.getName().replace(".txt", "");
            listModel.addElement(nama);
        }
    }
}

    
    private void simpanCatatan() {
    try {
        String judul = txtJudul.getText().trim();
        String isi = txtIsi.getText();

        if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Judul tidak boleh kosong!");
            return;
        }

        File file = new File("catatan/" + judul + ".txt");
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(isi);
        }

        if (!listModel.contains(judul)) {
            listModel.addElement(judul);
        }

        JOptionPane.showMessageDialog(this, "Catatan berhasil disimpan!");

    } catch (HeadlessException | IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan catatan!");
    }
}


    
    private void bukaCatatan(String judul) {
    try {
        File file = new File("catatan/" + judul + ".txt");

        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "Catatan tidak ditemukan.");
            return;
        }

        StringBuilder isi;
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            isi = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                isi.append(line).append("\n");
            }
        }

        txtJudul.setText(judul);
        txtIsi.setText(isi.toString());

    } catch (HeadlessException | IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal membuka catatan!");
    }
}

   private void hapusCatatan() {
    try {
        String judul = txtJudul.getText().trim();
        if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih catatan yang ingin dihapus!");
            return;
        }

        File file = new File("catatan/" + judul + ".txt");
        if (file.exists()) {
            file.delete();
        }

        listModel.removeElement(judul);

        txtJudul.setText("");
        txtIsi.setText("");

        JOptionPane.showMessageDialog(this, "Catatan berhasil dihapus!");

    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus catatan!");
    }
}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatatanHarianFrame().setVisible(true));
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImpor;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblcari;
    private javax.swing.JList<String> listCatatan;
    private javax.swing.JScrollPane scrollIsi;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtIsi;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
